<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    
    <xacro:property name="base_length" value="0.6" />
    <xacro:property name="base_width" value="0.4" />
    <xacro:property name="base_height" value="0.2" />
    <xacro:property name="wheel_radius" value="0.1" />
    <xacro:property name="wheel_length" value="0.05" />
    
    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
            <material name="green_b" />
        </visual>
        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
        </collision>
        <xacro:box_inertia 
            m="5.0" 
            l="${base_length}" w="${base_width}" h="${base_height}"
            xyz="0 0 ${wheel_radius}" rpy="0 0 0"
        />
        
    </link>

    <link name="right_wheel_link">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}" />
            </geometry>
            <origin xyz="0 -0.025 0" rpy="${pi / 2.0} 0 0"/>
            <material name="purple_r" />
        </visual>
        <collision>
           <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}" />
            </geometry>
            <origin xyz="0 -0.025 0" rpy="${pi / 2.0} 0 0"/>
        </collision>
        <xacro:cylinder_inertia
            m="1.0"
            r="${wheel_radius}"
            h="${wheel_length}"
            xyz="0 -0.025 0" 
            rpy="${pi / 2.0} 0 0"
        />
    </link>

    <link name="left_wheel_link">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}" />
            </geometry>
            <origin xyz="0 0.025 0" rpy="${pi / 2.0} 0 0"/>
            <material name="purple_l" />
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}" />
            </geometry>
            <origin xyz="0 0.025 0" rpy="${pi / 2.0} 0 0"/>
        </collision>
        <xacro:cylinder_inertia 
            m="1.0"
            r="${wheel_radius}"
            h="${wheel_length}"
            xyz="0 0.025 0" 
            rpy="${pi / 2.0} 0 0"         
        />
    </link>

    <link name="castor_wheel">
        <visual>
            <geometry>
                <sphere radius="${wheel_radius / 2.0}" />
            </geometry>
            <origin xyz="0 0 0" />
            <material name="green_b" />
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius / 2.0}" />
            </geometry>
            <origin xyz="0 0 0" />
        </collision>
        <xacro:sphere_inertia
            m="0.5"
            r="${wheel_radius / 2.0}"
            xyz="0 0 0"
        />
    </link>

    <link name="base_footprint">
        <origin xyz="0 0 0" />
    </link>

    <link name="blueRov">
        <visual>
            <geometry>
                <!-- 
                <mesh filename="package://neptune_2_description/meshes/blueRov2.dae" />
                       $(find neptune_2_description)    -->
               
                <mesh filename="file://$(find neptune_2_description)/meshes/blueRov2.dae" />
               
           </geometry>
            <!--
            <origin xyz="0.0 0.0 -0.05" rpy="${pi} 0 ${pi / 2}" />
            -->
            <origin xyz="0.0 0.0 -0.18" rpy="0 0 ${pi / 2}" />
           <!-- <material name="light_gray" /> -->
        </visual>
        <collision> 
            <origin xyz="0.0 0.0 -0.18" rpy="0 0 ${pi / 2}" />
            <geometry>
                <box size="0.340 0.457 0.254"/>
            </geometry>
        </collision>
        <xacro:box_inertia 
            m="10"
            l="0.340" w="0.457" h="0.254"
            xyz="0.0 0.0 -0.18" rpy="0 0 0"
        />
    </link>
    <joint name="joint_base_blueRov" type="fixed">
        <origin xyz="0 0 0.37" rpy=" 0 0 0"/> <!--{pi} 0 ${pi / 2} -->
        <parent link="base_link"/>
        <child link="blueRov"/>
        <axis xyz="0 1 0"/>
    </joint>
    
    <joint name="base_joint" type="fixed">
        <parent link="base_footprint" />
        <child link="base_link" />
        <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0" />        
    </joint>

    <joint name="base_right_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="right_wheel_link"/>
        <origin xyz ="${-base_length / 4.0} -0.225 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="base_left_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="left_wheel_link"/>
        <origin xyz ="${-base_length / 4.0} 0.225 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="base_castor_wheel" type="fixed">
        <parent link="base_link" />
        <child link="castor_wheel" />
        <origin xyz="${base_length / 3.0} 0 ${-wheel_radius / 2.0}" />
    </joint>
</robot>